apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
    app: mariadb
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  nfs:
    server: 192.168.1.108 #Replace this with 10.10.15.5 or 10.10.15.9 or 10.10.15.34 as your per login
    path: /var/nfs/jegan/mariadb #Replace this path with your nfs path /var/nfs/user[xy]/mariadb
