apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
    app: wordpress
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  nfs:
    server: 10.10.15.35 #Replace this with 10.10.15.27 or 10.10.15.34 as per your server IP 
    path: /var/nfs/jegan/share2 #Replace this path with your nfs path /var/nfs/user[xy]/share2
